project_id = "yfwgegapmggwywrnzqvg"

[functions.memory-interview-webhook]
verify_jwt = false

[functions.memory-interview-voice]
verify_jwt = false

[functions.memory-interview-stream-status]
verify_jwt = false

[functions.generate-memory-story]
verify_jwt = true

[functions.process-document-v2]
verify_jwt = true

[functions.regenerate-summary-v2]
verify_jwt = true

[functions.admin-rebuild-search]
verify_jwt = true

[functions.admin-reindex]
verify_jwt = true

[functions.admin-search-reindex]
verify_jwt = true

[functions.admin-user-management]
verify_jwt = true

[functions.create-next-recurring-task]
verify_jwt = true

[functions.demo-auth]
verify_jwt = false

[functions.demo-analytics]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-send]
verify_jwt = true

[functions.notify]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.regenerate-summary]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.validate-document]
verify_jwt = true

[functions.twilio-voice-webhook]
verify_jwt = false

[functions.twilio-voice-pin-verify]
verify_jwt = false

[functions.enhanced-twilio-pin-verify]
verify_jwt = false

[functions.enhanced-twilio-voice-chat]
verify_jwt = false

[functions.enhanced-twilio-group-selection]
verify_jwt = false

[functions.enhanced-twilio-webhook]
verify_jwt = false

[functions.sign-document-download]
verify_jwt = true

[functions.upload-and-process-document-v2]
verify_jwt = true

[functions.debug-extract-text]
verify_jwt = false

[functions.debug-gemini-health]
verify_jwt = false

[functions.initiate-scheduled-interviews]
verify_jwt = false

[functions.test-twilio-audio]
verify_jwt = false

[functions.test-twilio-audio-connect]
verify_jwt = false
