project_id = "yfwgegapmggwywrnzqvg"

[functions.notify]
verify_jwt = true

[functions.process-document]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.gmail-oauth]
verify_jwt = false

[functions.gmail-send]
verify_jwt = true
