// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwgegapmggwywrnzqvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd2dlZ2FwbWdnd3l3cm56cXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTAwMjUsImV4cCI6MjA3MDQ2NjAyNX0.YZWYq0S020M_ZPKQoarcz9LczAI_nEk4b3BbCLnSaWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});